### ISSUE TITLE
Merge hardware and software in notebook examples

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#53]
## Description
Merge hardware and software in notebook examples

Something like
```py
client = BlindAiClient()

# Comment this line for hardware mode
client.connect_server(addr="localhost", simulation=True)

# Comment this line for simulation mode
client.connect_server(
    addr="localhost",
    policy="policy.toml",
    certificate="host_server.pem"
)
```

## Why this modification is needed?

Make the notebooks clearer, and less redundant

## What documents need to be updated

- [ ] Main README
- [ ] CONTRIBUTING guidelines
- [ ] BlindAI Client README
- [ ] BlindAI Server README
- [ ] BlindAI Client CHANGELOG
- [ ] BlindAI Server CHANGELOG
- [ ] Python Docstrings 
- [x] others => python examples

## Additional Information
None

## Checklist

- [x] This issue concerns BlindAI Client
- [ ] This issue concerns BlindAI Server

**Comment by dhuynh95** [comment]
One person I talked to suggested we read information from an environment variable to know if the client should discuss with a simulation or hardware backend. I think default behavior should be simulation so that it always works but with a warning. 

If the user wants to talk to a hardware backend, we could ask them to specify an environment variable like _BLINDAI_CERTIFICATES_ which could point to a folder where there is a certificate and a policy file. If this environment variable does not exist or the folder is empty, it would go to simulation mode. 

This way we can provide the same API everywhere.

What do you guys think @cchudant @JoFrost ?

**Comment by cchudant** [comment]
I don't know whether this is a good idea.
This feels strange to me and not typical of library like that.

I think it's better to have simulation=True/False on connect?

As for the notebook examples, I think we should remove the hardware one and just have a comment where you need to change True to False?

**Comment by dhuynh95** [comment]
Ok yeah true, maybe just remove hardware / software notebooks and put comments.

What do you think of getting the certificate and policy from env variable?

**Comment by clauverjat** [comment]
Closing since #56 solves the issue
