### ISSUE TITLE
Failed to load model, the model or the input format are perhaps invalid

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#54]
## Description

This is due to BlindAI not supporting integer tensor output yet.
This was reported on discord, more info & the model are available there.

### Expected behavior:

Model runs

### Actual behavior:

Fails with error `Failed to load model, the model or the input format are perhaps invalid`

## Steps to Reproduce

The notebook: https://cdn.discordapp.com/attachments/965734276593242202/965734464690978866/Confidential_STT.ipynb
Input: https://cdn.discordapp.com/attachments/965734276593242202/965734464892313640/hello_world.wav 

## Blindai Versions

last docker version & probably on master too

## Additional Information

None

## Screenshots (if appropriate):

None

**Comment by JoFrost** [comment]
Will handle it

**Comment by JoFrost** [comment]
The issue was coming from a wrong input format. The input format specified was int64 while the model was expecting float32 datas.
However, this revealed an other issue: BlindAI was forcefully converting the output data to float32, while the model give a tensor of int64. This has been fixed in the PR #60, which allows to specify the output type of data.
